const str1 = "PrAjwal";
const str2 = "In,gA,le"; /*
console.log("toLowerCase()", str1.toLowerCase());
console.log("toLocaleLowerCase()", str1.toLocaleLowerCase());
console.log("toUpperCase()", str1.toUpperCase());
console.log("toLocaleUpperCase()", str1.toLocaleUpperCase());
console.log("concat(str2)", str1.concat(str2));
console.log('lastIndexOf("in")', str1.lastIndexOf("aj"));
console.log('match("pra")', str2.match("pra"));
console.log("replace(str2)", str1.replace(str2), str2);
console.log('trim("ale")', str2.trim("ale"), str2);
console.log("substring(2, 4)", str2.substring(2, 4));
console.log("slice(1, 4)", str1.slice(1, 4));
console.log('split(" ")', str2.split(","));
console.log('includes("pr")', str1.includes("pr"));
console.log('endsWith("wal")', str1.endsWith("wal"));
console.log("charAt(5)", str2.charAt(3));
console.log("charCodeAt(8)", str2.charCodeAt(3));
console.log("codePointAt(1)", str1.codePointAt(1));
console.log("indexOf(2)", str1.indexOf(2));
console.log("length", str1.length);
*/
// console.log('<br>lastIndexOf("in")', str2.lastIndexOf("In"));
// console.log('<br>match("pra")', str1.match("Pra"));
// console.log("<br>concat(str2)", str1.concat(str2));
//console.log("<br>replace(str2)", str2.replace(str1), str2);
//console.log('<br>trim("ale")', str2.trim(""), str2);
// console.log("<br>toUpperCase()", str1.toUpperCase());
// console.log("<br>toLowerCase()", str1.toLowerCase());
//console.log("<br>codePointAt(1)", str1.codePointAt(2));
//console.log("<br>substring(2, 4)", str2.substring(4, 10));
// console.log("<br>toLocaleUpperCase()", str1.toLocaleUpperCase());
// console.log("<br>toLocaleLowerCase()", str1.toLocaleLowerCase());
//console.log("<br>slice(1, 4)", str1.slice(1, 4));
// console.log('<br>split("")', str2.split(","));
// console.log(Array.from("Demo"));
// console.log("<br>charCodeAt(5)", str1.charCodeAt(5));
// console.log("<br>indexOf(r)", str1.indexOf("r"));
// console.log('<br>includes("pr")', str1.includes("rAj"));
// console.log('<br>endsWith("wal")', str1.endsWith("wal"));
// console.log("<br>charAt(5)", str1.charAt(5));
console.log("<br>length", str1.length);
